watch_stylesheet: true
watch_config: true

bars:
  yasb-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true
      acrylic: true
      dark: true
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:   ["komorebi_workspaces", "komorebi_active_layout", "active_window"]
      center: ["clock"]
      right:  ["weather-korea","weather","wifi","cpu", "memory", "battery"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      time_remaining_natural: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
        label: "{%H:%M %Z}"
        label_alt: "{%d-%m-%y %H:%M:%S %Z}"
        timezones: ["Asia/Ho_Chi_Minh","Europe/London", "America/New_York"]
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\uf200 {info[percent][total]}%"
      label_alt: "\uf200 CPU: {info[percent][total]}% | freq: {info[freq][current]:.2f} Mhz"
      update_interval: 5000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 10

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
        label: "\ue266 {virtual_mem_percent}%"
        label_alt: "\ue266 Available {virtual_mem_free}/{virtual_mem_total}"
        update_interval: 5000
        callbacks:
          on_right: "exec cmd /c Taskmgr"
        memory_thresholds:
          low: 25
        # ^ The percentage at which the .status-low CSS class is applied. Accepts integer from 0 to 100
          medium: 60
        # ^ The percentage at which the .status-medium CSS class is applied. Accepts integer from 0 to 100
          high: 95
        # ^ The percentage at which the .status-high CSS class is applied. Accepts integer from 0 to 100

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{index} {name}"
        label_default_name: "{index} {name}"
        label_zero_index: false
        hide_empty_workspaces: false

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "[\\\\]"
        columns: "[||]"
        rows: "[==]"
        vertical_stack: "[V]="
        horizontal_stack: "[H]="
        ultrawide_vertical_stack: "||="
        monocle: "[M]"
        maximised: "[X]"
        floating: "><>"
        paused: "[P]"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
        label: "{wifi_icon}"
        label_alt: "{wifi_icon} {wifi_name}"
        update_interval: 5000
        wifi_icons:
          - "\udb82\udd2e"  # 0% strength (no wifi)
          - "\udb82\udd1f"  # 1-25% strength
          - "\udb82\udd22"  # 26-50% strength
          - "\udb82\udd25"  # 51-75% strength
          # - "\udb82\udd28"  # 76-100% strength. Alternate theming: \uf1eb
          - "\uf1eb"  # 76-100% strength. Alternate theming: \uf1eb
        callbacks:
          on_right: "exec cmd.exe /c start ms-settings:network"


  # Some custom widgets

  explorer_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf07c"
      label_alt: "Explorer"
      class_name: "explorer-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec explorer.exe"
        on_right: "toggle_label"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf3c5 {data[city]}, {data[region]}"
      label_alt: "\uf3c5 {data[ip]} [{data[country]}]"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000                                        # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl"                           # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0c2 VI {data[current_condition][0][temp_C]}\u00b0c"
      label_alt: "\uf0c2 {data[current_condition][0][weatherDesc][0][value]}"
      class_name: "weather-widget"
      exec_options:
        run_cmd: "curl.exe wttr.in/HoChiMinh?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"
      callbacks:
        on_right: "exec_custom"

  weather-korea:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0c2 KO {data[current_condition][0][temp_C]}\u00b0c"
      label_alt: "\uf0c2 {data[current_condition][0][weatherDesc][0][value]}"
      class_name: "weather-widget"
      exec_options:
        run_cmd: "curl.exe  wttr.in/Seoul?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"
      callbacks:
        on_right: "exec_custom"

